### ISSUE TITLE
Spotlight active window

### ISSUE THREAD

**Issue by zsoltk** [bumble-tech/appyx#221]
This is a 2.0 scope proposal.

**Current situation**

`Spotlight` supports only a single element to be considered `ACTIVE`.

**Use-cases where this isn't good**

- There's some padding on the main element, and the edges of prev / next elements should already be visible (window = 3)
- There's a visual emphasis on the main element, but many other elements are visible, all of them are relatively small (window = n)

**Proposal**

1. Let's extend the possible states to: `INACTIVE_BEFORE`, `ACTIVE_BEFORE`, `CENTERPIECE`, `ACTIVE_AFTER`, `INACTIVE_AFTER`
2. Let's have a `windowSize` constructor argument to `Spotlight` with default = 1
3. (Probably apply a check that it can't be less than 1 and should be an odd number)
4. Based on the `windowSize`, all operations maintain a window of 1 `CENTERPIECE` + `(windowSize - 1) / 2` * `ACTIVE_BEFORE` + `(windowSize - 1) / 2` * `ACTIVE_AFTER` states
5. `OnScreenResolver` can be straightforward, `INACTIVE_BEFORE` & `INACTIVE_AFTER`-> `false`, the rest of them `true`, it's just that sometimes there will be zero `ACTIVE_BEFORE` / `ACTIVE_AFTER` elements, and sometimes it will be a non-zero amount, maintained by the navmodel.

**Extras**

1. To make it flexible rather than baked in, let's have a new operation to change the window size. It can figure out which elements to switch between `INACTIVE_BEFORE` <-> `ACTIVE_BEFORE` as needed based on if they fit in the new window or not.
2. UI can do layout measurements, and calculate how many elements will fit on the screen. This is then reported this to `Spotlight` via the new operation.
3. Consider making the states a `sealed class` instead of `enum class` to have indices for before / after states – this requires more attention to proper state maintenance as a one-off investment, but will make UI logic probably a lot easier

**Comment by CherryPerry** [comment]
Looks like we need API changes how we use `OnScreenResolver` for lifecycle purposes.
Currently it is pretty simple – `OnScreenResolver` returns true, then the node is capped by `RESUMED`, otherwise by `CREATED` state.

What I **definitely** do not want is to have `ACTIVE_BEFORE` and `ACTIVE_AFTER` nodes to be in `RESUMED` state. This was a huge issue in `androidx.ViewPager` for a long time until Google has finally added functionality to cap the fragments on the sides by `STARTED` state (search for `setMaxLifecycle` in `FragmentPagerAdapter`).

Currently we use `STARTED` state for our tracking implementation, so we should be able to choose between `STARTED` and `CREATED` cap.

**Comment by zsoltk** [comment]
Closing as no longer relevant. We went with an entirely different approach using camera/geometry + runtime calculated visibility directly dependent on ui = we don't need to represent this in the model state anymore.
