### ISSUE TITLE
Remainder of gesture operation doesn't settle

### ISSUE THREAD

**Issue by zsoltk** [bumble-tech/appyx#495]
**Scenario:**

- Drag longer than 100% in any model (e.g. puzzle 15 element drag)

**ER:**

- Even without #494, if the drag gets interpreted as more than one operation, it should settle after the gesture

**AR:**

- The state is left hanging with some amount of drag, it doesn't settle
- As a consequence, no other operations can be applied until manually settled (which might make it feel like it's unresponsive)

**Comment by manuel-martos** [comment]
The underlying problem here is that the `ElementUiModel` being dragged, when it reaches over 100% progress, the excess is transferred to another `ElementUiModel`, which consumes and applies that excess, but the management of the drag is not transferred from the initial `ElementUiModel` to the new one. 
cc: @zsoltk
